set_property IOSTANDARD LVCMOS33 [get_ports {output[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports bt_signal]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports idle_light]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN V10 [get_ports rst]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports {output[0]}]
set_property PACKAGE_PIN K15 [get_ports {output[1]}]
set_property PACKAGE_PIN J13 [get_ports {output[2]}]
set_property PACKAGE_PIN N14 [get_ports {output[3]}]
set_property PACKAGE_PIN R18 [get_ports {output[4]}]
set_property PACKAGE_PIN V17 [get_ports {output[5]}]
set_property PACKAGE_PIN U17 [get_ports {output[6]}]
set_property PACKAGE_PIN U16 [get_ports {output[7]}]
set_property PACKAGE_PIN D14 [get_ports bt_signal]

set_property MARK_DEBUG false [get_nets {output_OBUF[0]}]
set_property MARK_DEBUG false [get_nets {output_OBUF[1]}]
set_property MARK_DEBUG false [get_nets {output_OBUF[2]}]
set_property MARK_DEBUG false [get_nets {output_OBUF[3]}]
set_property MARK_DEBUG false [get_nets {output_OBUF[4]}]
set_property MARK_DEBUG false [get_nets {output_OBUF[5]}]
set_property MARK_DEBUG false [get_nets {output_OBUF[6]}]
set_property MARK_DEBUG false [get_nets {output_OBUF[7]}]
set_property MARK_DEBUG false [get_nets {b_reg[0]}]
set_property MARK_DEBUG false [get_nets {b_reg[1]}]
set_property MARK_DEBUG false [get_nets {b_reg[2]}]
set_property MARK_DEBUG false [get_nets {b_reg[3]}]
set_property MARK_DEBUG false [get_nets {b_reg[4]}]
set_property MARK_DEBUG false [get_nets {b_reg[5]}]
set_property MARK_DEBUG false [get_nets {b_reg[6]}]
set_property MARK_DEBUG false [get_nets {b_reg[7]}]
connect_debug_port u_ila_0/clk [get_nets [list {controller/output_reg[7]}]]


set_property MARK_DEBUG false [get_nets {controller/clk16_reg_reg[3]}]
set_property MARK_DEBUG false [get_nets {controller/Q[0]}]
set_property MARK_DEBUG false [get_nets {controller/Q[1]}]
set_property MARK_DEBUG false [get_nets {controller/Q[2]}]
set_property MARK_DEBUG false [get_nets {controller/Q[3]}]
set_property MARK_DEBUG false [get_nets {controller/Q[4]}]
set_property MARK_DEBUG false [get_nets {controller/Q[5]}]
set_property MARK_DEBUG false [get_nets {controller/Q[6]}]
set_property MARK_DEBUG false [get_nets {controller/Q[7]}]

set_property MARK_DEBUG false [get_nets {controller/s_reg[4]}]
set_property MARK_DEBUG false [get_nets {controller/s_reg[0]}]
set_property MARK_DEBUG false [get_nets {controller/s_reg[1]}]
set_property MARK_DEBUG false [get_nets {controller/s_reg[2]}]
set_property MARK_DEBUG false [get_nets {controller/s_reg[3]}]

set_property MARK_DEBUG true [get_nets bt_signal_IBUF]
connect_debug_port u_ila_0/probe0 [get_nets [list bt_signal_IBUF]]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets low_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property PACKAGE_PIN U11 [get_ports pause]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports pause]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN V11 [get_ports idle_light]
set_property PACKAGE_PIN B11 [get_ports hsync]
set_property PACKAGE_PIN B12 [get_ports vsync]
set_property PACKAGE_PIN B7 [get_ports {blue[0]}]
set_property PACKAGE_PIN C7 [get_ports {blue[1]}]
set_property PACKAGE_PIN C6 [get_ports {green[0]}]
set_property PACKAGE_PIN A5 [get_ports {green[1]}]
set_property PACKAGE_PIN B6 [get_ports {green[2]}]
set_property PACKAGE_PIN A3 [get_ports {red[0]}]
set_property PACKAGE_PIN B4 [get_ports {red[1]}]
set_property PACKAGE_PIN C5 [get_ports {red[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports start_game]
set_property PACKAGE_PIN U12 [get_ports start_game]
